# Generated by Django 5.0.3 on 2024-03-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Subject',
            new_name='subject',
        ),
    ]
